name: TestLoop
options:
  bundleIdPrefix: com.sylab
  deploymentTarget:
    iOS: "16.0"
targets:
  TestLoop:
    type: application
    platform: iOS
    sources: [.]
    settings:
      base:
        CODE_SIGNING_ALLOWED: "NO"
        CODE_SIGN_IDENTITY: ""
        GENERATE_INFOPLIST_FILE: "YES"
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: "YES"
